---
title: "Flexdashboard Shiny Tutorial"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny # with shiny we make the dashboard a dynamic one
---

```{r setup, include=FALSE}
source("utils.R")
source("packages.R")
```

```{r}
# Make data
set.seed(123)
sales_data_tbl <- tibble(
  date  = seq.Date(from = ymd("2018-01-01"), to = today(), length.out = 90),
  class = sample(c("marketing", "sales", "research"), size = 90, replace = TRUE),
  sales = runif(n = 90, min = 1, max = 100)
)
```

<!-- 
We want to create a dashboard that looks like this:
- a sidebar with three inputs (a date input, a check box input and a slider input)
- a reset button  
- one column with three sections printing the inputs values
- one column with two sections showing the filtered data and a summary of the filtered data
-->

<!-- This is an empty template to create the dashboard live. !!!!!!!!!! -->
<!-- Clear all the content after the lecture. !!!!!!!!!!!!!!!!!!!!!!!!! -->


Sidebar {.sidebar}
------------------------

```{r}
checkboxGroupInput(
  inputId = "checkbox_group", # inside in this list we are creating the check box
  label = h4("Checkbox Group"),
  choices = c(
    "Marketing" = "marketing",
    "R&D" = "research",
    "Sales" = "sales"
  ),
  selected = c("marketing", "research", "sales")
)

dateRangeInput(
  inputId = "date_range",
  label = h4("Date Range"),
  start = "2018-01-01",
  end = today(), 
  min = min(sales_data_tbl$date),
  max = max(sales_data_tbl$date),
  startview = "year"
)

sliderInput(
  inputId = "slider_input",
  label = h4("Slider Range"),
  min = 1,
  max = 100,
  value = c(40, 60),
  step = 1,
  round = TRUE,
  pre = "$"
)
```

```{r reset}
actionButton(
  inputId = "reset",
  label = "Reset",
  icon = icon("sync")
)

observeEvent( # reset button encapsulated into a observe event
  eventExpr = input$reset,
  handlerExpr = {

    updateCheckboxGroupInput(
      session  = session,
      inputId  = "checkbox_group",
      selected = c("marketing", "research", "sales")
    )

    updateDateRangeInput(
      session = session,
      inputId = "date_range",
      start = min(sales_data_tbl$date),
      end = today()
    )

    updateSliderInput(
      session = session,
      inputId = "slider_input",
      value = c(40, 60)
    )

  }
)
```



Column {data-width=400}
-----------------------

### Section - Checkbox Output

```{r}
# checkboxGroupInput: Creates a set of checkboxes for user selection
# renderPrint: Generates the text output based on the selected checkboxes
# verbatimTextOutput: Displays the text generated by renderPrint in the UI

output$checkbox_values <- renderPrint(input$checkbox_group) # store the result of the input made by the user in the check box

textOutput(outputId = "checkbox_values") # we want to output the result of output$checkbox_values
```


### Section - Date Range

```{r}
output$date_range_values <- renderPrint(input$date_range)

textOutput(outputId = "date_range_values")
```


### Section - Slider Output

```{r}
output$slider_values <- renderPrint(input$slider_input)

textOutput(outputId = "slider_values")
```



Column {data-width=600}
-----------------------

```{r}
# Reactive filter based on the input choices 
sales_data_filtered <- reactive({
  sales_data_tbl %>%
    filter(class %in% input$checkbox_group) %>%
    filter(date %>% between(ymd(input$date_range[1]), ymd(input$date_range[2]))) %>%
    filter(sales %>% between(input$slider_input[1], input$slider_input[2]))
})
```


### Section - Reactive Output

```{r}
output$tab_output <- renderTable(sales_data_filtered()) # when we want to render or use a reactive object we have to use it as a function, so with ()
tableOutput(outputId = "tab_output")
```


### Section - Reactive Summary

```{r}
output$dt_output_2 <- DT::renderDataTable(expr = {
  sales_data_filtered() %>%
    group_by(class) %>%
    summarise(total_revenue = sum(sales)) %>%
    ungroup() %>%
    mutate(total_revenue = scales::dollar(total_revenue))
}, options = list(scrollY = "250px"))

DTOutput(outputId = "dt_output_2")
```

